testGroups.push({
  name: 'Lineage prayers (Morning Prayers)',
  includeInPercentage: true,
  sentences: true,
  tests: [
    { tibetan: 'ཀུན་བཟང་རྡོར་སེམས་དགའ་རབ་ཤྲཱི་སེང་༔ ', transliteration: "künzang dorsem garap shiri seng" },
    { tibetan: 'པདྨ་ཀ་རཱ་རྗེ་འབངས་ཉི་ཤུ་ལྔ༔ ', transliteration: "padma kara jembang nyishu nga" },
    { tibetan: 'སོ་ཟུར་གནུབས་གཉགས་གཏེར་སྟོན་བརྒྱ་རྩ་སོགས༔ ', transliteration: "sosur nupnyak tertön gyatsa sok" },
    { tibetan: 'བཀའ་གཏེར་བླ་མ་རྣམས་ལ་གསོལ་བ་འདེབས༔ ', transliteration: "kater lama namla sölwa dep" },
    { tibetan: 'ཨོ་རྒྱན་སངས་རྒྱས་གཉིས་པའི་ཐུགས་ཀྱི་སྲས། །', transliteration: "orgyen sang-gyé nyipé thuk-kyi sé" },
    { tibetan: 'གཏེར་འབྱིན་གྲུབ་ཐོབ་རྒྱ་མཚོའི་འཁོར་ལོས་བསྒྱུར། །', transliteration: "terjin trupthop gyamtsö khorlö gyur" },
    { tibetan: 'རྣམ་ཐར་བསམ་ཡས་སྙིགས་དུས་བསྟན་འགྲོའི་མགོན། །', transliteration: "namthar samyé nyiktü tendrö gön" },
    { tibetan: 'མཆོག་གྱུར་གླིང་པའི་ཞབས་ལ་གསོལ་བ་འདེབས། །', transliteration: "chok-kyur lingpé zhapla sölwa dep" },
    { tibetan: 'སྔོན་ཚེ་རིག་འཛིན་ནུས་ལྡན་རྡོ་རྗེ་རྩལ། །', transliteration: "ngöntsé rikdzin nüden dorjé tsel" },
    { tibetan: 'མ་འོངས་བདེ་གཤེགས་མོས་པ་མཐའ་ཡས་ཞབས། །', transliteration: "ma-ong déshek möpa thayé zhap" },
    { tibetan: 'ད་ལྟ་པད་འབྱུང་རྒྱལ་ཚབ་འདྲོག་བན་དངོས། །', transliteration: "tata péjung gyeltsap drokpen ngö" },
    { tibetan: 'འཇིགས་བྲལ་ཡེ་ཤེས་རྡོ་རྗེར་གསོལ་བ་འདེབས། །', transliteration: "jiktrel yéshé dorjer sölwa dep" },
    { tibetan: 'སངས་རྒྱས་ཀུན་གྱི་མཁྱེ༵ན་གཉིས་ཡེ་ཤེས་གཟུགས། །', transliteration: "sang-gyé künkyi khyen-nyi yéshé zuk" },
    { tibetan: 'བརྩེ༵་ཆེན་ཡེ་ཤེས་རྣམ་རོལ་འཇམ་དཔལ་དབྱངས། །', transliteration: "tséchen yéshé namröl jampel yang" },
    { tibetan: 'ཐུབ་བསྟན་ཤིང་རྟ་མཁས་གྲུབ་དབང་པོ་ཆེ། །', transliteration: "thupten shingta khétrup wangpo ché" },
    { tibetan: 'པ༵དྨ་མདོ༵་སྔག༵ས་གླིང༵་པར༵་གསོལ་བ་འདེབས། །', transliteration: "padma do-ngak lingpar sölwa dep" },
    { tibetan: 'ང༵ག་དབ༵ང་སྲས་བཅས་རྒྱལ་ཀུན་དགྱེས་པའི་ལམ། །', transliteration: "ngakwang séché gyelkün gyépé lam" },
    { tibetan: 'དོན་གྱི་གྲག༵ས་པ༵་མཐའ་ཡས་འབྱུང་བའི་གཞི། །', transliteration: "tönkyi trakpa thayé jungwé zhi" },
    { tibetan: 'གསན་བསམ་སྒོམ་པས་ཐུབ་བསྟན་ལེགས་འཛིན་བཤེས། །', transliteration: "sensam gompé thupten lekdzin shé" },
    { tibetan: 'དགེ༵་ལེ༵གས་དཔ༵ལ་འབ༵ར་ཞབས་ལ་གསོལ་བ་འདེབས། །', transliteration: "gélek pelbar zhapla sölwa dep" },
    { tibetan: 'འོག་མིན་ཆོས་ཀྱི་དབྱིངས་ཀྱི་ཕོ་བྲང་ནས། །', transliteration: "omin chökyi yingkyi p'otrang né" },
    { tibetan: 'དུས་གསུམ་སངས་རྒྱས་ཀུན་གྱི་ངོ་བོ་ཉིད། །', transliteration: "tüsum sang-gyé künkyi ngowo nyi" },
    { tibetan: 'རང་སེམས་ཆོས་སྐུར་མངོན་སུམ་སྟོན་མཛད་པ། །', transliteration: "rangsem chökur ngönsum töndzé pa" },
    { tibetan: 'རྩ་བའི་བླ་མའི་ཞབས་ལ་གསོལ་བ་འདེབས།། །།', transliteration: "tsawé lamé zhapla sölwa dep" },
  ]
});