testGroups.push({
  name: 'Trashi Gyepa',
  includeInPercentage: true,
  sentences: true,
  tests: [
    { tibetan: 'ༀ།', transliteration: "om" },
    { tibetan: 'སྣང་སྲིད་རྣམ་དག་རང་བཞིན་ལྷུན་གྲུབ་པའི། །', transliteration: "nangsi namtak rangzhin lhüntrup pé"  },
    { tibetan: 'བཀྲ་ཤིས་ཕྱོགས་བཅུའི་ཞིང་ན་བཞུགས་པ་ཡི། །', transliteration: "trashi chokchü zhing-na zhukpa yi" },
    { tibetan: 'སངས་རྒྱས་ཆོས་དང་དགེ་འདུན་འཕགས་པའི་ཚོགས། །', transliteration: "sang-gyé chötang gendün p'akpé tsok" },
    { tibetan: 'ཀུན་ལ་ཕྱག་འཚལ་བདག་ཅག་བཀྲ་ཤིས་ཤོག །', transliteration: "künla chaktsel dachak trashi sho" },
    { tibetan: 'སྒྲོལ་མའི་རྒྱལ་པོ་རྩལ་བརྟན་དོན་གྲུབ་དགོངས། །', transliteration: "drölmé gyelpo tselten töntrup gong" },
    { tibetan: 'བྱམས་པའི་རྒྱན་དཔལ་དགེ་གྲགས་དཔལ་དམ་པ། །', transliteration: "champé gyenpel gétrak peltam pa" },
    { tibetan: 'ཀུན་ལ་དགོངས་པ་རྒྱ་ཆེར་གྲགས་པ་ཅན། །', transliteration: "künla gongpa gyacher trakpa chen"  },
    { tibetan: 'ལྷུན་པོ་ལྟར་འཕགས་རྩལ་གྲགས་དཔལ་དང་ནི། །', transliteration: "lhünpo tarp'ak tseltrak peltang ni" },
    { tibetan: 'སེམས་ཅན་ཐམས་ཅད་ལ་དགོངས་གྲགས་པའི་དཔལ། །', transliteration: "semchen thamché lagong trakpé pel" },
    { tibetan: 'ཡིད་ཚིམ་མཛད་པ་རྩལ་རབ་གྲགས་དཔལ་ཏེ། །', transliteration: "yitsim dzépa tselrap trakpel té"  },
    { tibetan: 'མཚན་ཙམ་ཐོས་པས་བཀྲ་ཤིས་དཔལ་འཕེལ་བ། །', transliteration: "tsentsam thöpé trashi pelp'el wa" },
    { tibetan: 'བདེ་བར་གཤེགས་པ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "déwar shekpa gyéla chaktsel lo" },
    { tibetan: 'འཇམ་དཔལ་གཞོན་ནུ་དཔལ་ལྡན་རྡོ་རྗེ་འཛིན། །', transliteration: "jampel zhön-nu pelden dorjé dzin" },
    { tibetan: 'སྤྱན་རས་གཟིགས་དབང་མགོན་པོ་བྱམས་པའི་དཔལ། །', transliteration: "chenré zikwang gönpo champé pel" },
    { tibetan: 'ས་ཡི་སྙིང་པོ་སྒྲིབ་པ་རྣམ་པར་སེལ། །', transliteration: "sayi nyingpo drip-pa nampar sel" },
    { tibetan: 'ནམ་མཁའི་སྙིང་པོ་འཕགས་མཆོག་ཀུན་ཏུ་བཟང་། །', transliteration: "namkhé nyingpo p'akchok küntu zang" },
    { tibetan: 'ཨུཏྤལ་རྡོ་རྗེ་པད་དཀར་ཀླུ་ཤིང་དང་། །', transliteration: "utpel dorjé pékar lushing tang" },
    { tibetan: 'ནོར་བུ་ཟླ་བ་རལ་གྲི་ཉི་མ་ཡི། །', transliteration: "norpu dawa reltri nyima yi" },
    { tibetan: 'ཕྱག་མཚན་ལེགས་བསྣམས་བཀྲ་ཤིས་དཔལ་གྱི་མཆོག །', transliteration: "chaktsen leknam trashi pelkyi chok" },
    { tibetan: 'བྱང་ཆུབ་སེམས་དཔའ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "changchup sempa gyéla chaktsel lo" },
    { tibetan: 'རིན་ཆེན་གདུགས་མཆོག་བཀྲ་ཤིས་གསེར་གྱི་ཉ། །', transliteration: "rinchen dukchok trashi serkyi nya" },
    { tibetan: 'འདོད་འབྱུང་བུམ་བཟང་ཡིད་འོང་ཀ་མ་ལ། །', transliteration: "döjung pumzang yi-ong kama la" },
    { tibetan: 'སྙན་གྲགས་དུང་དང་ཕུན་ཚོགས་དཔལ་བེའུ། །', transliteration: "nyentrak tungtang p'üntsok pelpé-u" },
    { tibetan: 'མི་ནུབ་རྒྱལ་མཚན་དབང་བསྒྱུར་འཁོར་ལོ་སྟེ། །', transliteration: "minup gyeltsen wang-gyur khorlo té"  },
    { tibetan: 'རིན་ཆེན་རྟགས་མཆོག་བརྒྱད་ཀྱི་ཕྱག་མཚན་ཅན། །', transliteration: "rinchen takchok gyékyi chaktsen chen"  },
    { tibetan: 'ཕྱོགས་དུས་རྒྱལ་བ་མཆོད་ཅིང་དགྱེས་བསྐྱེད་མ། །', transliteration: "choktü gyelwa chöching gyékyé ma" },
    { tibetan: 'སྒེགས་སོགས་ངོ་བོ་དྲན་པའི་དཔལ་འཕེལ་བ། །', transliteration: "geksok ngowo trenpé pelp'el wa" },
    { tibetan: 'བཀྲ་ཤིས་ལྷ་མོ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "trashi lhamo gyéla chaktsel lo" },
    { tibetan: 'ཚངས་པ་ཆེན་པོ་བདེ་འབྱུང་སྲེད་མེད་བུ། །', transliteration: "tsangpa chenpo déjung sémé pu" },
    { tibetan: 'མིག་སྟོང་ལྡན་དང་རྒྱལ་པོ་ཡུལ་འཁོར་སྲུང་། །', transliteration: "miktong dentang gyelpo yülkhor sung" },
    { tibetan: 'འཕགས་སྐྱེས་པོ་དང་ཀླུ་དབང་མིག་མི་བཟང་། །', transliteration: "p'ak-kyé potang luwang mikmi zang" },
    { tibetan: 'རྣམ་ཐོས་སྲས་ཏེ་ལྷ་རྫས་འཁོར་ལོ་དང་། །', transliteration: "namthö sété lhadzé khorlo tang" },
    { tibetan: 'ཏྲི་ཤུ་ལ་དང་མདུང་ཐུང་རྡོ་རྗེ་ཅན། །', transliteration: "trishu latang dungthung dorjé chen"  },
    { tibetan: 'པི་ཝཾ་རལ་གྲི་མཆོད་རྟེན་རྒྱལ་མཚན་འཛིན། །', transliteration: "piwam reltri chorten gyeltsen dzin" },
    { tibetan: 'ས་གསུམ་གནས་སུ་བཀྲ་ཤིས་དགེ་ལེགས་འཕེལ། །', transliteration: "sasum nésu trashi gélek p'el" },
    { tibetan: 'འཇིག་རྟེན་སྐྱོང་བ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "jikten kyongwa gyéla chaktsel lo" },
    { tibetan: 'བདག་ཅག་དེང་འདིར་བྱ་བ་རྩོམ་པ་ལ། །', transliteration: "dachak tengdir chawa tsompa la" },
    { tibetan: 'བགེགས་དང་ཉེ་བར་འཚེ་བ་ཀུན་ཞི་ནས། །', transliteration: "gektang nyéwar tséwa künzhi né"  },
    { tibetan: 'འདོད་དོན་དཔལ་འཕེལ་བསམ་དོན་ཡིད་བཞིན་འགྲུབ། །', transliteration: "dötön pelp'el samtön yizhin drup" },
    { tibetan: 'བཀྲ་ཤིས་བདེ་ལེགས་ཕུན་སུམ་ཚོགས་པར་ཤོག', transliteration: "trashi délek p'ünsum tsokpar sho" }
  ]
})