testGroups.push({
  name: 'The Seven Diamond Verses',
  includeInPercentage: true,
  sentences: true,
  tests: [
    { tibetan: 'ༀ།', transliteration: "om" },
    { tibetan: 'སྣང་སྲིད་རྣམ་དག་རང་བཞིན་ལྷུན་གྲུབ་པའི། །', transliteration: "nangsi namtak rangzhin lhüntrup pe" },
    { tibetan: 'བཀྲ་ཤིས་ཕྱོགས་བཅུའི་ཞིང་ན་བཞུགས་པ་ཡི། །', transliteration: "trashi chokchü zhingna zhukpa yi" },
    { tibetan: 'སངས་རྒྱས་ཆོས་དང་དགེ་འདུན་འཕགས་པའི་ཚོགས། །', transliteration: "sangye chötang gendün pakpe tsok" },
    { tibetan: 'ཀུན་ལ་ཕྱག་འཚལ་བདག་ཅག་བཀྲ་ཤིས་ཤོག །', transliteration: "künla chaktsal dachak trashi sho" },
    { tibetan: 'སྒྲོལ་མའི་རྒྱལ་པོ་རྩལ་བརྟན་དོན་གྲུབ་དགོངས། །', transliteration: "drölme gyalpo tsalten töntrup gong" },
    { tibetan: 'བྱམས་པའི་རྒྱན་དཔལ་དགེ་གྲགས་དཔལ་དམ་པ། །', transliteration: "champe gyenpal getrak paltam pa" },
    { tibetan: 'ཀུན་ལ་དགོངས་པ་རྒྱ་ཆེར་གྲགས་པ་ཅན། །', transliteration: "künla gongpa gyacher trakpa chen" },
    { tibetan: 'ལྷུན་པོ་ལྟར་འཕགས་རྩལ་གྲགས་དཔལ་དང་ནི། །', transliteration: "lhünpo tarpak tsaltrak paltang ni" },
    { tibetan: 'སེམས་ཅན་ཐམས་ཅད་ལ་དགོངས་གྲགས་པའི་དཔལ། །', transliteration: "semchen tamche la gong trakpe pal" },
    { tibetan: 'ཡིད་ཚིམ་མཛད་པ་རྩལ་རབ་གྲགས་དཔལ་ཏེ། །', transliteration: "yitsim dzepa tsalrap trakpal te" },
    { tibetan: 'མཚན་ཙམ་ཐོས་པས་བཀྲ་ཤིས་དཔལ་འཕེལ་བ། །', transliteration: "tsentsam töpe trashi palp'el wa" },
    { tibetan: 'བདེ་བར་གཤེགས་པ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "dewar shekpa gyela chaktsal lo" },
    { tibetan: 'འཇམ་དཔལ་གཞོན་ནུ་དཔལ་ལྡན་རྡོ་རྗེ་འཛིན། །', transliteration: "jampal shönu palden dorje dzin" },
    { tibetan: 'སྤྱན་རས་གཟིགས་དབང་མགོན་པོ་བྱམས་པའི་དཔལ། །', transliteration: "chenrezik wang gönpo champe pal" },
    { tibetan: 'ས་ཡི་སྙིང་པོ་སྒྲིབ་པ་རྣམ་པར་སེལ། །', transliteration: "sayi nyingpo dripa nampar sel" },
    { tibetan: 'ནམ་མཁའི་སྙིང་པོ་འཕགས་མཆོག་ཀུན་ཏུ་བཟང་། །', transliteration: "namkhe nyingpo pakchok kuntu zang" },
    { tibetan: 'ཨུཏྤལ་རྡོ་རྗེ་པད་དཀར་ཀླུ་ཤིང་དང་། །', transliteration: "utpal dorje pekar lushing tang" },
    { tibetan: 'ནོར་བུ་ཟླ་བ་རལ་གྲི་ཉི་མ་ཡི། །', transliteration: "norpu dawa raltri nyima yi" },
    { tibetan: 'ཕྱག་མཚན་ལེགས་བསྣམས་བཀྲ་ཤིས་དཔལ་གྱི་མཆོག །', transliteration: "chaktsen leknam trashi palkyi chok" },
    { tibetan: 'བྱང་ཆུབ་སེམས་དཔའ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "changchup sempa gyela chaktsal lo" },
    { tibetan: 'རིན་ཆེན་གདུགས་མཆོག་བཀྲ་ཤིས་གསོར་གྱི་ཉ། །', transliteration: "rinchen dukchok trashi serkyi nya" },
    { tibetan: 'འདོད་འབྱུང་བུམ་བཟང་ཡིད་འོང་ཀ་མ་ལ། །', transliteration: "döjung pumzang yi ong kamala" },
    { tibetan: 'སྙན་གྲགས་དུང་དང་ཕུན་ཚོགས་དཔལ་བེའུ། །', transliteration: "nyentrak tungtang püntsok palbe-u" },
    { tibetan: 'མི་ནུབ་རྒྱལ་མཚན་དབང་བསྒྱུར་འཁོར་ལོ་སྟེ། །', transliteration: "minup gyaltsen wangyur khorlo te" },
    { tibetan: 'རིན་ཆེན་རྟགས་མཆོག་བརྒྱད་ཀྱི་ཕྱག་མཚན་ཅན། །', transliteration: "rinchen takchok gyekyi chaktsen chen" },
    { tibetan: 'ཕྱོགས་དུས་རྒྱལ་བ་མཆོད་ཅིང་དགྱེས་བསྐྱེད་མ། །', transliteration: "choktü gyalwa chöching gyekye ma" },
    { tibetan: 'སྒེགས་སོགས་ངོ་བོ་དྲན་པའི་དཔལ་འཕེལ་བ། །', transliteration: "geksok ngowo trenpe palp'el wa" },
    { tibetan: 'བཀྲ་ཤིས་ལྷ་མོ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "trashi lhamo gyela chaktsal lo" },
    { tibetan: 'ཚངས་པ་ཆེན་པོ་བདེ་འབྱུང་སྲེད་མེད་བུ། །', transliteration: "tsangpa chenpo dejung seme pu" },
    { tibetan: 'མིག་སྟོང་ལྡན་དང་རྒྱལ་པོ་ཡུལ་འཁོར་སྲུང་། །', transliteration: "miktong dentang gyalpo yülkhor sung" },
    { tibetan: 'འཕགས་སྐྱེས་པོ་དང་ཀླུ་དབང་མིག་མི་བཟང་། །', transliteration: "p'akye potang luwang mikmi zang" },
    { tibetan: 'རྣམ་ཐོས་སྲས་ཏེ་ལྷ་རྫས་འཁོར་ལོ་དང་། །', transliteration: "namthö sete lhadze khorlo tang" },
    { tibetan: 'ཏྲི་ཤུ་ལ་དང་མདུང་ཐུང་རྡོ་རྗེ་ཅན། །', transliteration: "trishu latang dungthung dorje chen" },
    { tibetan: 'པི་ཝཾ་རལ་གྲི་མཆོད་རྟེན་རྒྱལ་མཚན་འཛིན། །', transliteration: "piwam raltri chorten gyaltsen dzin" },
    { tibetan: 'ས་གསུམ་གནས་སུ་བཀྲ་ཤིས་དགེ་ལེགས་འཕེལ། །', transliteration: "sasum nesu trashi gelek pel" },
    { tibetan: 'འཇིག་རྟེན་སྐྱོང་བ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "jikten kyongwa gyela chaktsal lo" },
    { tibetan: 'བདག་ཅག་དེང་འདིར་བྱ་བ་རྩོམ་པ་ལ། །', transliteration: "dachak tengdir chawa tsompa la" },
    { tibetan: 'བགེགས་དང་ཉེ་བར་འཚེ་བ་ཀུན་ཞི་ནས། །', transliteration: "gektang nyewar tsewa künzhi ne" },
    { tibetan: 'འདོད་དོན་དཔལ་འཕེལ་བསམ་དོན་ཡིད་བཞིན་འགྲུབ། །', transliteration: "dötön palp'el samtön yizhin drup" },
    { tibetan: 'བཀྲ་ཤིས་བདེ་ལེགས་ཕུན་སུམ་ཚོགས་པར་ཤོག', transliteration: "trashi delek p'ünsum tsokpar sho" }
  ]
})