testGroups.push({
  name: 'French — Trashi Gyepa',
  setting: 'french',
  includeInPercentage: true,
  sentences: true,
  tests: [
    { tibetan: 'ༀ།', transliteration: "om" },
    { tibetan: 'སྣང་སྲིད་རྣམ་དག་རང་བཞིན་ལྷུན་གྲུབ་པའི། །', transliteration: "nangsi namtak rangshin lhuntroup pé" },
    { tibetan: 'བཀྲ་ཤིས་ཕྱོགས་བཅུའི་ཞིང་ན་བཞུགས་པ་ཡི། །', transliteration: "trachi tch'oktchu shing-na shoukpa yi" },
    { tibetan: 'སངས་རྒྱས་ཆོས་དང་དགེ་འདུན་འཕགས་པའི་ཚོགས། །', transliteration: "sang-guié tch'eutang guendun p'akpé ts'ok" },
    { tibetan: 'ཀུན་ལ་ཕྱག་འཚལ་བདག་ཅག་བཀྲ་ཤིས་ཤོག །', transliteration: "kunla tch'akts'el datchak trachi cho" },
    { tibetan: 'སྒྲོལ་མའི་རྒྱལ་པོ་རྩལ་བརྟན་དོན་གྲུབ་དགོངས། །', transliteration: "dreulmé guielpo tselten teuntroup gong" },
    { tibetan: 'བྱམས་པའི་རྒྱན་དཔལ་དགེ་གྲགས་དཔལ་དམ་པ། །', transliteration: "tch'ampé guienpel guétrak peltam pa" },
    { tibetan: 'ཀུན་ལ་དགོངས་པ་རྒྱ་ཆེར་གྲགས་པ་ཅན། །', transliteration: "kunla gongpa guiatch'er trakpa tchen" },
    { tibetan: 'ལྷུན་པོ་ལྟར་འཕགས་རྩལ་གྲགས་དཔལ་དང་ནི། །', transliteration: "lhunpo tarp'ak tseltrak peltang ni" },
    { tibetan: 'སེམས་ཅན་ཐམས་ཅད་ལ་དགོངས་གྲགས་པའི་དཔལ། །', transliteration: "semtchen t'amtché lagong trakpé pel" },
    { tibetan: 'ཡིད་ཚིམ་མཛད་པ་རྩལ་རབ་གྲགས་དཔལ་ཏེ། །', transliteration: "yits'im dzépa tselrap trakpel té" },
    { tibetan: 'མཚན་ཙམ་ཐོས་པས་བཀྲ་ཤིས་དཔལ་འཕེལ་བ། །', transliteration: "ts'entsam t'eupé trachi pelp'el wa" },
    { tibetan: 'བདེ་བར་གཤེགས་པ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "déwar chekpa guiéla tch'akts'el lo" },
    { tibetan: 'འཇམ་དཔལ་གཞོན་ནུ་དཔལ་ལྡན་རྡོ་རྗེ་འཛིན། །', transliteration: "djampel sheun-nou pelden dordjé dzin" },
    { tibetan: 'སྤྱན་རས་གཟིགས་དབང་མགོན་པོ་བྱམས་པའི་དཔལ། །', transliteration: "tchenré zikwang gueunpo tch'ampé pel" },
    { tibetan: 'ས་ཡི་སྙིང་པོ་སྒྲིབ་པ་རྣམ་པར་སེལ། །', transliteration: "sayi nyingpo drip-pa nampar sel" },
    { tibetan: 'ནམ་མཁའི་སྙིང་པོ་འཕགས་མཆོག་ཀུན་ཏུ་བཟང་། །', transliteration: "namkhé nyingpo p'aktch'ok kuntou zang" },
    { tibetan: 'ཨུཏྤལ་རྡོ་རྗེ་པད་དཀར་ཀླུ་ཤིང་དང་། །', transliteration: "outpel dordjé pékar louching tang" },
    { tibetan: 'ནོར་བུ་ཟླ་བ་རལ་གྲི་ཉི་མ་ཡི། །', transliteration: "norpou dawa reltri nyima yi" },
    { tibetan: 'ཕྱག་མཚན་ལེགས་བསྣམས་བཀྲ་ཤིས་དཔལ་གྱི་མཆོག །', transliteration: "tch'akts'en leknam trachi pelkyi tch'ok" },
    { tibetan: 'བྱང་ཆུབ་སེམས་དཔའ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "tch'angtch'oup sempa guiéla tch'akts'el lo" },
    { tibetan: 'རིན་ཆེན་གདུགས་མཆོག་བཀྲ་ཤིས་གསེར་གྱི་ཉ། །', transliteration: "rintch'en douktch'ok trachi serkyi nya" },
    { tibetan: 'འདོད་འབྱུང་བུམ་བཟང་ཡིད་འོང་ཀ་མ་ལ། །', transliteration: "deudjoung poumzang yi-ong kama la" },
    { tibetan: 'སྙན་གྲགས་དུང་དང་ཕུན་ཚོགས་དཔལ་བེའུ། །', transliteration: "nyentrak toungtang p'unts'ok pelpé-ou" },
    { tibetan: 'མི་ནུབ་རྒྱལ་མཚན་དབང་བསྒྱུར་འཁོར་ལོ་སྟེ། །', transliteration: "minoup guielts'en wang-guiour khorlo té" },
    { tibetan: 'རིན་ཆེན་རྟགས་མཆོག་བརྒྱད་ཀྱི་ཕྱག་མཚན་ཅན། །', transliteration: "rintch'en taktch'ok guiékyi tch'akts'en tchen" },
    { tibetan: 'ཕྱོགས་དུས་རྒྱལ་བ་མཆོད་ཅིང་དགྱེས་བསྐྱེད་མ། །', transliteration: "tch'oktu guielwa tch'eutching guiékyé ma" },
    { tibetan: 'སྒེགས་སོགས་ངོ་བོ་དྲན་པའི་དཔལ་འཕེལ་བ། །', transliteration: "gueksok ngowo trenpé pelp'el wa" },
    { tibetan: 'བཀྲ་ཤིས་ལྷ་མོ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "trachi lhamo guiéla tch'akts'el lo" },
    { tibetan: 'ཚངས་པ་ཆེན་པོ་བདེ་འབྱུང་སྲེད་མེད་བུ། །', transliteration: "ts'angpa tch'enpo dédjoung sémé pou" },
    { tibetan: 'མིག་སྟོང་ལྡན་དང་རྒྱལ་པོ་ཡུལ་འཁོར་སྲུང་། །', transliteration: "miktong dentang guielpo yulkhor soung" },
    { tibetan: 'འཕགས་སྐྱེས་པོ་དང་ཀླུ་དབང་མིག་མི་བཟང་། །', transliteration: "p'ak-kyé potang louwang mikmi zang" },
    { tibetan: 'རྣམ་ཐོས་སྲས་ཏེ་ལྷ་རྫས་འཁོར་ལོ་དང་། །', transliteration: "namt'eu sété lhadzé khorlo tang" },
    { tibetan: 'ཏྲི་ཤུ་ལ་དང་མདུང་ཐུང་རྡོ་རྗེ་ཅན། །', transliteration: "trichou latang doungt'oung dordjé tchen" },
    { tibetan: 'པི་ཝཾ་རལ་གྲི་མཆོད་རྟེན་རྒྱལ་མཚན་འཛིན། །', transliteration: "piwam reltri tch'orten guielts'en dzin" },
    { tibetan: 'ས་གསུམ་གནས་སུ་བཀྲ་ཤིས་དགེ་ལེགས་འཕེལ། །', transliteration: "sassoum néssou trachi guélek p'el" },
    { tibetan: 'འཇིག་རྟེན་སྐྱོང་བ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', transliteration: "djikten kyongwa guiéla tch'akts'el lo" },
    { tibetan: 'བདག་ཅག་དེང་འདིར་བྱ་བ་རྩོམ་པ་ལ། །', transliteration: "datchak tengdir tch'awa tsompa la" },
    { tibetan: 'བགེགས་དང་ཉེ་བར་འཚེ་བ་ཀུན་ཞི་ནས། །', transliteration: "guektang nyéwar ts'éwa kunshi né" },
    { tibetan: 'འདོད་དོན་དཔལ་འཕེལ་བསམ་དོན་ཡིད་བཞིན་འགྲུབ། །', transliteration: "deuteun pelp'el samteun yishin droup" },
    { tibetan: 'བཀྲ་ཤིས་བདེ་ལེགས་ཕུན་སུམ་ཚོགས་པར་ཤོག', transliteration: "trachi délek p'unsoum ts'okpar cho" }
  ]
})
