testGroups.push({
  name: 'Prefixed mono-syllables',
  tests: [
    // Gao
    { tibetan: 'གཅའ', transliteration: 'cha' },
    { tibetan: 'གཉའ', transliteration: 'nya' },
    { tibetan: 'གཏའ', transliteration:  'ta' },
    { tibetan: 'གདའ', transliteration:  'da' },
    { tibetan: 'གནའ', transliteration:  'na' },
    { tibetan: 'གཙའ', transliteration: 'tsa' },
    { tibetan: 'གཞའ', transliteration: 'zha' },
    { tibetan: 'གཟའ', transliteration:  'za' },
    { tibetan: 'གཡའ', transliteration:  'ya' },
    { tibetan: 'གཤའ', transliteration: 'sha' },
    { tibetan: 'གསའ', transliteration:  'sa' },

    // Dao
    { tibetan: 'དཀའ', transliteration:  'ka' },
    { tibetan: 'དགའ', transliteration:  'ga' },
    { tibetan: 'དངའ', transliteration: 'nga' },
    { tibetan: 'དཔའ', transliteration:  'pa' },
    { tibetan: 'དབའ', transliteration:  'wa' },
    { tibetan: 'དམའ', transliteration:  'ma' },
    { tibetan: 'དཀྱ', transliteration: 'kya' },
    { tibetan: 'དགྱ', transliteration: 'gya' },
    { tibetan: 'དབྱ', transliteration:  'ya' },
    { tibetan: 'དམྱ', transliteration: 'nya' },
    { tibetan: 'དཀྲ', transliteration: 'tra' },
    { tibetan: 'དཔྲ', transliteration: 'tra' },
    { tibetan: 'དབྲ', transliteration: 'dra' },

    // Bao
    { tibetan: 'བཀའ',  transliteration:  'ka' },
    { tibetan: 'བགའ',  transliteration:  'ga' },
    { tibetan: 'བཅའ',  transliteration: 'cha' },
    { tibetan: 'བཏའ',  transliteration:  'ta' },
    { tibetan: 'བདའ',  transliteration:  'da' },
    { tibetan: 'བཙའ',  transliteration: 'tsa' },
    { tibetan: 'བཞའ',  transliteration: 'zha' },
    { tibetan: 'བཟའ',  transliteration:  'za' },
    { tibetan: 'བཤའ',  transliteration: 'sha' },
    { tibetan: 'བསའ',  transliteration:  'sa' },
    { tibetan: 'བཀྱ',  transliteration: 'kya' },
    { tibetan: 'བགྱ',  transliteration: 'gya' },
    { tibetan: 'བཀྲ',  transliteration: 'tra' },
    { tibetan: 'བགྲ',  transliteration: 'dra' },
    { tibetan: 'བརླ',  transliteration:  'la' },
    { tibetan: 'བསླ',  transliteration:  'la' },
    { tibetan: 'བརྐ',  transliteration:  'ka' },
    { tibetan: 'བརྒ',  transliteration:  'ga' },
    { tibetan: 'བརྔ',  transliteration: 'nga' },
    { tibetan: 'བརྗ',  transliteration:  'ja' },
    { tibetan: 'བརྙ',  transliteration: 'nya' },
    { tibetan: 'བརྟ',  transliteration:  'ta' },
    { tibetan: 'བརྡ',  transliteration:  'da' },
    { tibetan: 'བརྣ',  transliteration:  'na' },
    { tibetan: 'བརྩ',  transliteration: 'tsa' },
    { tibetan: 'བརྫ',  transliteration: 'dza' },
    { tibetan: 'བལྟ',  transliteration:  'ta' },
    { tibetan: 'བསྐ',  transliteration:  'ka' },
    { tibetan: 'བསྒ',  transliteration:  'ga' },
    { tibetan: 'བསྔ',  transliteration: 'nga' },
    { tibetan: 'བསྙ',  transliteration: 'nya' },
    { tibetan: 'བསྟ',  transliteration:  'ta' },
    { tibetan: 'བསྡ',  transliteration:  'da' },
    { tibetan: 'བསྣ',  transliteration:  'na' },
    { tibetan: 'བསྩ',  transliteration: 'tsa' },
    { tibetan: 'བརྐྱ', transliteration: 'kya' },
    { tibetan: 'བརྒྱ', transliteration: 'gya' },
    { tibetan: 'བསྐྱ', transliteration: 'kya' },
    { tibetan: 'བསྒྱ', transliteration: 'gya' },
    { tibetan: 'བསྐྲ', transliteration: 'tra' },
    { tibetan: 'བསྒྲ', transliteration: 'dra' },

    // Mao
    { tibetan: 'མཁའ', transliteration:  'kha' },
    { tibetan: 'མགའ', transliteration:   'ga' },
    { tibetan: 'མངའ', transliteration:  'nga' },
    { tibetan: 'མཅའ', transliteration:  'cha' },
    { tibetan: 'མཇའ', transliteration:   'ja' },
    { tibetan: 'མཉའ', transliteration:  'nya' },
    { tibetan: 'མཐའ', transliteration:  'tha' },
    { tibetan: 'མདའ', transliteration:   'da' },
    { tibetan: 'མནའ', transliteration:   'na' },
    { tibetan: 'མཚའ', transliteration:  'tsa' },
    { tibetan: 'མཛའ', transliteration:  'dza' },
    { tibetan: 'མཁྱ', transliteration: 'khya' },
    { tibetan: 'མཀྲ', transliteration:  'tra' },
    { tibetan: 'མཁྲ', transliteration: "tr'a" },
    { tibetan: 'མགྲ', transliteration:  'dra' },

    // Ao
    { tibetan: 'འཁའ', transliteration:  'kha' },
    { tibetan: 'འགའ', transliteration:   'ga' },
    { tibetan: 'འཆའ', transliteration:  'cha' },
    { tibetan: 'འཇའ', transliteration:   'ja' },
    { tibetan: 'འཐའ', transliteration:  'tha' },
    { tibetan: 'འདའ', transliteration:   'da' },
    { tibetan: 'འཕའ', transliteration:  "p'a" },
    { tibetan: 'འབའ', transliteration:   'ba' },
    { tibetan: 'འཚའ', transliteration:  'tsa' },
    { tibetan: 'འཛའ', transliteration:  'dza' },
    { tibetan: 'འཁྱ', transliteration: 'khya' },
    { tibetan: 'འགྱ', transliteration:  'gya' },
    { tibetan: 'འཕྱ', transliteration:  'cha' },
    { tibetan: 'འབྱ', transliteration:   'ja' },
    { tibetan: 'འཁྲ', transliteration: "tr'a" },
    { tibetan: 'འགྲ', transliteration:  'dra' },
    { tibetan: 'འདྲ', transliteration:  'dra' },
    { tibetan: 'འཕྲ', transliteration: "tr'a" },
    { tibetan: 'འབྲ', transliteration:  'dra' },

    // A few cases with syllables
    { tibetan: 'བཀི',  transliteration:  'ki' },
    { tibetan: 'བགི',  transliteration:  'gi' },
    { tibetan: 'བགའ',  transliteration:  'ga' },
    { tibetan: 'བངི',  transliteration: 'ngi' },
    { tibetan: 'བཇི',  transliteration:  'ji' },
    { tibetan: 'བཉི',  transliteration: 'nyi' },
    { tibetan: 'བཏི',  transliteration:  'ti' },
    { tibetan: 'བདི',  transliteration:  'di' },
    { tibetan: 'བནི',  transliteration:  'ni' },
    { tibetan: 'དབི',  transliteration:   'i' },
    { tibetan: 'བམི',  transliteration:  'mi' },
    { tibetan: 'བཙི',  transliteration: 'tsi' },
    { tibetan: 'བཛི',  transliteration: 'dzi' },
  ]
})